### ISSUE TITLE
something error in  Domino 9.0.1 environment

### ISSUE THREAD

**Issue by gahg96** [camac/DominoDebugPlugin#2]
I setup a Domino 9.0.1 Server in Windows, Eclipse luna, when I finished debug configuration, restart Domino HTTP Server, it prompt the error msg:

> l http
> 2015/05/21 17:50:27   Informational, rebuilding view - user specified REBUILD (reading C:\Program Files\IBM\Domino\data\names.nsf view note Title:'($Servers)')
> 2015/05/21 17:50:28   HTTP Server: Using Web Configuration View
> 2015/05/21 17:50:30   JVM: Java Virtual Machine initialized.
> 2015/05/21 17:50:30   HTTP Server: Java Virtual Machine loaded
> 2015/05/21 17:50:30   HTTP Server: DSAPI Domino Off-Line Services HTTP extension Loaded successfully
> 2015/05/21 17:50:31   HTTP JVM: CLFAD0325I: WARNING: Using pde configuration Domino OSGI located in C:\Program Files\IBM\Domino\data\domino\workspace\pde.launch.ini
> 2015/05/21 17:50:31   HTTP JVM: Logging ConsoleHandler enabled because system running in dev mode
> 2015/05/21 17:50:31   HTTP JVM: com.ibm.domino.http.bootstrap.osgi.LaunchOSGIException: java.lang.reflect.InvocationTargetException
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.osgi.LaunchRCP.startRCP(LaunchRCP.java:345)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.osgi.LaunchRCP.launchOSGIFramework(LaunchRCP.java:172)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.BootstrapOSGIClassLoader.launchOSGIFramework(BootstrapOSGIClassLoader.java:79)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.BootstrapOSGIClassLoader.loadClass(BootstrapOSGIClassLoader.java:63)
> 2015/05/21 17:50:31   HTTP JVM:     at java.lang.ClassLoader.loadClass(ClassLoader.java:638)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.BootstrapClassLoader.findClass(BootstrapClassLoader.java:79)
> 2015/05/21 17:50:31   HTTP JVM: Caused by: 
> 2015/05/21 17:50:31   HTTP JVM: java.lang.reflect.InvocationTargetException
> 2015/05/21 17:50:31   HTTP JVM:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2015/05/21 17:50:31   HTTP JVM:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
> 2015/05/21 17:50:31   HTTP JVM:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
> 2015/05/21 17:50:31   HTTP JVM:     at java.lang.reflect.Method.invoke(Method.java:611)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.osgi.LaunchRCP.startRCP(LaunchRCP.java:342)
> 2015/05/21 17:50:31   HTTP JVM:     ... 5 more
> 2015/05/21 17:50:31   HTTP JVM: Caused by: 
> 2015/05/21 17:50:31   HTTP JVM: java.lang.RuntimeException: The activator org.eclipse.osgi.internal.framework.SystemBundleActivator for bundle org.eclipse.osgi is invalid
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:291)
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.osgi.framework.internal.core.StartLevelManager.launch(StartLevelManager.java:247)
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.osgi.framework.internal.core.SystemBundle.resume(SystemBundle.java:201)
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:644)
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.osgi.framework.internal.core.OSGi.launch(OSGi.java:51)
> 2015/05/21 17:50:31   HTTP JVM:     at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:313)
> 2015/05/21 17:50:31   HTTP JVM:     ... 10 more
> 2015/05/21 17:50:31   HTTP JVM: java.lang.ClassNotFoundException
> 2015/05/21 17:50:31   HTTP JVM:     at java.lang.ClassLoader.findClass(ClassLoader.java:377)
> 2015/05/21 17:50:31   HTTP JVM:     at java.lang.ClassLoader.loadClass(ClassLoader.java:672)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.BootstrapOSGIClassLoader.loadClass(BootstrapOSGIClassLoader.java:68)
> 2015/05/21 17:50:31   HTTP JVM:     at java.lang.ClassLoader.loadClass(ClassLoader.java:638)
> 2015/05/21 17:50:31   HTTP JVM:     at com.ibm.domino.http.bootstrap.BootstrapClassLoader.findClass(BootstrapClassLoader.java:79)
> 2015/05/21 17:50:31   Xsp Initialization error - Could not load class or methods
> 2015/05/21 17:50:35   HTTP Server: Started

Could you kindly help to give some suggestions how to avoid it,Thank you very much!

**Comment by camac** [comment]
Hi there, sorry for the late reply.
I can't think of a solution. 
When you created the debug launch did you make sure the Target Platform plugins were deselected?
Also are did you make sure auto-start was false?

**Comment by camac** [comment]
Closing, I assume everything is working ok.
Note: the latest [XPages SDK](https://www.openntf.org/main.nsf/project.xsp?r=project/XPages%20SDK%20for%20Eclipse%20RCP) should be used from now in instead of this project
